vars_with_no_parents = ['MINVOLSET', 'DISCONNECT', 'PULMEMBOLUS', 'INTUBATION', 'KINKEDTUBE', 'FIO2', 'ANAPHYLAXIS',
                        'INSUFFANESTH', 'LVFAILURE', 'HYPOVOLEMIA', 'ERRLOWOUTPUT', 'ERRCAUTER']
