order_array = ['MINVOLSET', 'DISCONNECT', 'PULMEMBOLUS', 'INTUBATION', 'KINKEDTUBE', 'FIO2', 'ANAPHYLAXIS',
               'INSUFFANESTH', 'LVFAILURE', 'HYPOVOLEMIA', 'ERRLOWOUTPUT', 'ERRCAUTER', 'VENTMACH', 'PAP',
               'SHUNT', 'VENTTUBE', 'VENTLUNG', 'MINVOL', 'VENTALV', 'PRESS', 'PVSAT', 'TPR', 'ARTCO2', 'SAO2',
               'CATECHOL', 'HISTORY', 'LVEDVOLUME', 'STROKEVOLUME', 'HR', 'HRBP', 'HRSAT', 'HREKG', 'CO', 'BP',
               'CVP', 'PCWP', 'EXPCO2']
