order_array2 = ['MINVOLSET', 'DISCONNECT', 'PULMEMBOLUS', 'INTUBATION', 'KINKEDTUBE', 'FIO2', 'ANAPHYLAXIS',
               'INSUFFANESTH', 'LVFAILURE', 'HYPOVOLEMIA', 'ERRLOWOUTPUT', 'ERRCAUTER', 'VENTMACH', 'PAP',
               'SHUNT', 'VENTTUBE', 'VENTLUNG', 'MINVOL', 'VENTALV', 'PRESS', 'PVSAT', 'TPR', 'ARTCO2', 'SAO2',
               'CATECHOL', 'HISTORY', 'LVEDVOLUME', 'STROKEVOLUME', 'HR', 'HRBP', 'HRSAT', 'HREKG', 'CO', 'BP',
               'CVP', 'PCWP', 'EXPCO2']

order_array = ['LVFAILURE', 'HYPOVOLEMIA', 'ERRLOWOUTPUT', 'ERRCAUTER', 'ANAPHYLAXIS', 'INTUBATION', 'FIO2',
                'PULMEMBOLUS', 'KINKEDTUBE', 'MINVOLSET', 'DISCONNECT', 'INSUFFANESTH', 'HISTORY', 'LVEDVOLUME',
                'STROKEVOLUME', 'TPR', 'PAP', 'SHUNT', 'VENTMACH', 'CVP', 'PCWP', 'VENTTUBE', 'PRESS', 'VENTLUNG',
                'MINVOL', 'VENTALV', 'PVSAT', 'ARTCO2', 'SAO2', 'EXPCO2', 'CATECHOL', 'HR', 'HRBP', 'HREKG', 'HRSAT',
                'CO', 'BP']
